Use new extension syntax
standardhealth/fsh-mcode pull request #120
Opened 2020-03-06 15:22 UTC by cmoesel

The upcoming SUSHI 0.10.0 uses a new syntax for using externally-defined (as opposed to inline) extensions.  This PR uses the new syntax, but ensures output is the same by using the same slice name as the extension name.

NOTE: Some changes are whitespace-only, as my editor automatically trims whitespace.

Marking as a DRAFT PR so it is not merged until SUSHI 0.10.0 is available.

2020-03-06 22:04 UTC, markkramerus requested changes
I would prefer that the local slice name for the standalone extensions should be camelCase.  For example, `* bodySite.extension contains Laterality named laterality 0..1`  (and subsequent references as extension[laterality]).

2020-03-07 03:22 UTC, cmoesel commented
OK.  I can change it to camelCase.  I did it the way I did it because:
(a) it caused output that was exactly the same as the prior behavior, and
(b) when I looked at other places in mCODE where slicing occurred (for example on components), it did _not_ user camelCase -- it used TitleCase.

2020-03-07 04:13 UTC, cmoesel commented
OK.  This has been updated to use camelCase, @markkramerus -- and now that SUSHI 0.10.0 was released, the CI passes as well.  Since you `requested changes`, I cannot merge this.  Feel free to merge if/when you approve of the changes.

2020-03-09 15:41 UTC, markkramerus approved these changes

2020-03-09 15:41 UTC, merged