ECOG and Karnofsky profiles
standardhealth/fsh-mcode pull request #7
Opened 2019-12-23 22:57 UTC by CarolinePotteiger

Added ECOG and Karnofsky mCODE profiles

2019-12-28 15:39 UTC, markkramerus requested changes
I did an update... do a pull on your branch before making further changes. 

1.	ECOG/Karn: basedOn – should be Reference(ServiceRequest  | CarePlan)
2.	ECOG/Karn: Category: Should we have a fixed value instead of letting the user choose one? If so, what is the correct category for performance status? #procedure? #exam?
3.	ECOG/Karn: focus only Reference(Resource) – this is not a diff. Remove.
4.	ECOG/Karn: encounter – do not constrain to US Core
5.	ECOG/Karn: performer – constrain to Practitioner, not USCorePractitioner
6.	ECOG/Karn: derivedFrom --- do not constrain. Remove.
7.	ECOG/Karn: I don’t see any reason to constrain interpretation to 0..1 from 0..*. Remove.’
8.	ECOG/Karn: These are so similar, maybe we should create a parent class that has everything except the code and valueCodeableConcept binding. I put them into the same file for that reason. Make sure you update (pull) your branch.
9.	ECOG/Karn example: onsetDateTime does not belong. It is effectiveDateTime.
10.	ECOG/Karn example: asserter does not belong. It is practitioner.
11.	ECOG/Karn example: Do not set the focus. The focus is the patient (already given in the subject), not a specific condition.
12.	ECOG/Karn example: Should we set the category? If so, what is the correct value?  See comment #2.
13.	ECOG/Karn example: If the method is always going to be * method = SCT#5880005 "Clinical examination", should this added to the profiles?
14.	In the procedure example, we don’t need both a reasonReference and a reasonCode. One or the other.
15.	The treatment intent in procedure examples should use the extension name to refer to the relevant slice:
* extension[TreatmentIntent].valueCodeableConcept = SCT#373808002 "Curative - procedure intent"

2020-01-02 16:32 UTC, CarolinePotteiger commented
I made the changes Mark suggested. 

For comment #2 and #12, in my mind, there could be multiple categories the physician used to determine the performance status such as procedure, laboratory, survey, and exam so I would think it's better to let the user choose one. However, I'm not exactly sure how physician's determine the status so I could be wrong. 

For comment #13, I picked the broad method of "clinical examination" because it encompasses multiple specific methods that could be used to determine these scores. However, the user may want to be specific in what methods he/she actually used.

2020-01-03 20:45 UTC, markkramerus commented on PerformanceStatus.fsh
> +* category only ObservationCategoryCodes (extensible)
* category from ObservationCategoryCodes (extensible)

2020-01-03 20:46 UTC, markkramerus commented on PerformanceStatus.fsh
> +* category only ObservationCategoryCodes (extensible)
Binding is always "from", not "only"

2020-01-03 20:46 UTC, markkramerus commented on PerformanceStatus.fsh
> +* encounter only Reference(Encounter)
Remove. Not sure why we constrain this.

2020-01-03 20:47 UTC, markkramerus commented on PerformanceStatus.fsh
> +* category only ObservationCategoryCodes (extensible)
Same as above (from)

2020-01-03 20:47 UTC, markkramerus commented on PerformanceStatus.fsh
> +* encounter only Reference(Encounter)
Same as above (remove)

2020-01-03 20:50 UTC, markkramerus requested changes
See comments on individual lines.

2020-01-06 15:07 UTC, markkramerus approved these changes

2020-01-06 15:12 UTC, merged